import type { Player, Position, Role } from "./types";

// Generated from docs/icons.md: slug, name, nation, positions, rating, role, person id.
// Davids and Okocha share a person id with their Premier League cards, so one
// XI can't hold both versions.
const ICONS: [string, string, string, string, number, Role, string][] = [
  ["lev-yashin", "Lev Yashin", "USSR", "GK", 94, "G", "icon:lev-yashin"],
  ["gianluigi-buffon", "Gianluigi Buffon", "Italy", "GK", 93, "G", "icon:gianluigi-buffon"],
  ["dino-zoff", "Dino Zoff", "Italy", "GK", 91, "G", "icon:dino-zoff"],
  ["oliver-kahn", "Oliver Kahn", "Germany", "GK", 91, "G", "icon:oliver-kahn"],
  ["gordon-banks", "Gordon Banks", "England", "GK", 90, "G", "icon:gordon-banks"],
  ["franz-beckenbauer", "Franz Beckenbauer", "Germany", "CB/CDM", 95, "D", "icon:franz-beckenbauer"],
  ["paolo-maldini", "Paolo Maldini", "Italy", "LB/CB", 94, "D", "icon:paolo-maldini"],
  ["franco-baresi", "Franco Baresi", "Italy", "CB", 93, "D", "icon:franco-baresi"],
  ["bobby-moore", "Bobby Moore", "England", "CB", 92, "D", "icon:bobby-moore"],
  ["fabio-cannavaro", "Fabio Cannavaro", "Italy", "CB", 91, "D", "icon:fabio-cannavaro"],
  ["alessandro-nesta", "Alessandro Nesta", "Italy", "CB", 91, "D", "icon:alessandro-nesta"],
  ["roberto-carlos", "Roberto Carlos", "Brazil", "LB/LWB", 91, "D", "icon:roberto-carlos"],
  ["cafu", "Cafu", "Brazil", "RB/RWB", 91, "D", "icon:cafu"],
  ["giacinto-facchetti", "Giacinto Facchetti", "Italy", "LB", 89, "D", "icon:giacinto-facchetti"],
  ["diego-maradona", "Diego Maradona", "Argentina", "CAM/CF", 95, "M", "icon:diego-maradona"],
  ["zinedine-zidane", "Zinedine Zidane", "France", "CAM/CM", 94, "M", "icon:zinedine-zidane"],
  ["bobby-charlton", "Bobby Charlton", "England", "CM/CAM", 93, "M", "icon:bobby-charlton"],
  ["michel-platini", "Michel Platini", "France", "CAM/CM", 93, "M", "icon:michel-platini"],
  ["xavi", "Xavi", "Spain", "CM", 93, "M", "icon:xavi"],
  ["andres-iniesta", "Andrés Iniesta", "Spain", "CM/LW", 93, "M", "icon:andres-iniesta"],
  ["lothar-matthaus", "Lothar Matthäus", "Germany", "CM/CDM", 92, "M", "icon:lothar-matthaus"],
  ["zico", "Zico", "Brazil", "CAM", 92, "M", "icon:zico"],
  ["roberto-baggio", "Roberto Baggio", "Italy", "CAM/CF", 92, "M", "icon:roberto-baggio"],
  ["andrea-pirlo", "Andrea Pirlo", "Italy", "CDM/CM", 91, "M", "icon:andrea-pirlo"],
  ["kaka", "Kaká", "Brazil", "CAM", 91, "M", "icon:kaka"],
  ["francesco-totti", "Francesco Totti", "Italy", "CAM/CF", 91, "M", "icon:francesco-totti"],
  ["frank-rijkaard", "Frank Rijkaard", "Netherlands", "CDM/CB", 90, "M", "icon:frank-rijkaard"],
  ["johan-neeskens", "Johan Neeskens", "Netherlands", "CM", 89, "M", "icon:johan-neeskens"],
  ["clarence-seedorf", "Clarence Seedorf", "Netherlands", "CM/CAM", 90, "M", "icon:clarence-seedorf"],
  ["edgar-davids", "Edgar Davids", "Netherlands", "CDM/CM", 89, "M", "pl:4068"],
  ["jayjay-okocha", "Jay-Jay Okocha", "Nigeria", "CAM/CM", 89, "M", "pl:6230"],
  ["lionel-messi", "Lionel Messi", "Argentina", "RW/CAM/CF", 95, "F", "icon:lionel-messi"],
  ["george-best", "George Best", "Northern Ireland", "RW/LW", 93, "F", "icon:george-best"],
  ["garrincha", "Garrincha", "Brazil", "RW", 93, "F", "icon:garrincha"],
  ["ronaldinho", "Ronaldinho", "Brazil", "LW/CAM", 93, "F", "icon:ronaldinho"],
  ["rivaldo", "Rivaldo", "Brazil", "LW/CAM", 91, "F", "icon:rivaldo"],
  ["pele", "Pelé", "Brazil", "CF/ST/CAM", 95, "F", "icon:pele"],
  ["johan-cruyff", "Johan Cruyff", "Netherlands", "CF/LW", 95, "F", "icon:johan-cruyff"],
  ["ferenc-puskas", "Ferenc Puskás", "Hungary", "ST/CF", 94, "F", "icon:ferenc-puskas"],
  ["alfredo-di-stefano", "Alfredo Di Stéfano", "Argentina", "CF/ST", 94, "F", "icon:alfredo-di-stefano"],
  ["ronaldo-r9", "Ronaldo (R9)", "Brazil", "ST", 94, "F", "icon:ronaldo-r9"],
  ["eusebio", "Eusébio", "Portugal", "ST", 93, "F", "icon:eusebio"],
  ["gerd-muller", "Gerd Müller", "Germany", "ST", 93, "F", "icon:gerd-muller"],
  ["marco-van-basten", "Marco van Basten", "Netherlands", "ST", 93, "F", "icon:marco-van-basten"],
  ["romario", "Romário", "Brazil", "ST", 92, "F", "icon:romario"],
  ["alessandro-del-piero", "Alessandro Del Piero", "Italy", "CF/ST", 91, "F", "icon:alessandro-del-piero"],
  ["kenny-dalglish", "Kenny Dalglish", "Scotland", "CF/ST", 91, "F", "icon:kenny-dalglish"],
  ["gary-lineker", "Gary Lineker", "England", "ST", 89, "F", "icon:gary-lineker"],
];

export const ICON_PLAYERS: Player[] = ICONS.map(([slug, name, nation, positions, rating, role, personId]) => ({
  key: `icon:${slug}`,
  personId,
  name,
  role,
  positions: positions.split("/") as Position[],
  nation,
  rating,
  season: null,
  club: null,
  icon: true,
  goalsPer90: role === "F" ? 0.7 : role === "M" ? 0.3 : role === "D" ? 0.06 : 0,
  apps: 0,
  goals: 0,
  assists: 0,
  minutes: 0,
  draftable: true,
}));
