/**
 * Generic club badges: a short code in the club's colours, so two players with the
 * same name can be told apart at a glance. No crests or logos.
 */
export interface ClubColours {
  code: string;
  bg: string;
  fg: string;
}

const CLUBS: Record<string, ClubColours> = {
  "AFC Bournemouth": { code: "BOU", bg: "#b50e12", fg: "#ffffff" },
  Arsenal: { code: "ARS", bg: "#ef0107", fg: "#ffffff" },
  "Aston Villa": { code: "AVL", bg: "#670e36", fg: "#95bfe5" },
  Barnsley: { code: "BAR", bg: "#d71920", fg: "#ffffff" },
  "Birmingham City": { code: "BIR", bg: "#1b3c8c", fg: "#ffffff" },
  "Blackburn Rovers": { code: "BLB", bg: "#009ee0", fg: "#ffffff" },
  Blackpool: { code: "BLP", bg: "#f68712", fg: "#ffffff" },
  "Bolton Wanderers": { code: "BOL", bg: "#ffffff", fg: "#263c7e" },
  "Bradford City": { code: "BRA", bg: "#8b1a3a", fg: "#f2b51c" },
  Brentford: { code: "BRE", bg: "#e30613", fg: "#ffffff" },
  "Brighton & Hove Albion": { code: "BHA", bg: "#0057b8", fg: "#ffffff" },
  Burnley: { code: "BUR", bg: "#6c1d45", fg: "#99d6ea" },
  "Cardiff City": { code: "CAR", bg: "#0070b5", fg: "#ffffff" },
  "Charlton Athletic": { code: "CHA", bg: "#d4021d", fg: "#ffffff" },
  Chelsea: { code: "CHE", bg: "#034694", fg: "#ffffff" },
  "Coventry City": { code: "COV", bg: "#59cbe8", fg: "#0b2a4a" },
  "Crystal Palace": { code: "CRY", bg: "#1b458f", fg: "#ff4d5e" },
  "Derby County": { code: "DER", bg: "#ffffff", fg: "#111111" },
  Everton: { code: "EVE", bg: "#003399", fg: "#ffffff" },
  Fulham: { code: "FUL", bg: "#ffffff", fg: "#111111" },
  "Huddersfield Town": { code: "HUD", bg: "#0e63ad", fg: "#ffffff" },
  "Hull City": { code: "HUL", bg: "#f5a12d", fg: "#111111" },
  "Ipswich Town": { code: "IPS", bg: "#3a64a3", fg: "#ffffff" },
  "Leeds United": { code: "LEE", bg: "#ffffff", fg: "#1d428a" },
  "Leicester City": { code: "LEI", bg: "#003090", fg: "#fdbe11" },
  Liverpool: { code: "LIV", bg: "#c8102e", fg: "#ffffff" },
  "Luton Town": { code: "LUT", bg: "#f78f1e", fg: "#002d62" },
  "Manchester City": { code: "MCI", bg: "#6cabdd", fg: "#1c2c5b" },
  "Manchester United": { code: "MUN", bg: "#da291c", fg: "#fbe122" },
  Middlesbrough: { code: "MID", bg: "#e11b22", fg: "#ffffff" },
  "Newcastle United": { code: "NEW", bg: "#111111", fg: "#ffffff" },
  "Norwich City": { code: "NOR", bg: "#fff200", fg: "#00843d" },
  "Nottingham Forest": { code: "NFO", bg: "#dd0000", fg: "#ffffff" },
  "Oldham Athletic": { code: "OLD", bg: "#004a9f", fg: "#ffffff" },
  Portsmouth: { code: "POR", bg: "#001489", fg: "#ffffff" },
  "Queens Park Rangers": { code: "QPR", bg: "#1d5ba4", fg: "#ffffff" },
  Reading: { code: "REA", bg: "#004494", fg: "#ffffff" },
  "Sheffield United": { code: "SHU", bg: "#ee2737", fg: "#ffffff" },
  "Sheffield Wednesday": { code: "SHW", bg: "#3b6eb4", fg: "#ffffff" },
  Southampton: { code: "SOU", bg: "#d71920", fg: "#ffffff" },
  "Stoke City": { code: "STK", bg: "#e03a3e", fg: "#ffffff" },
  Sunderland: { code: "SUN", bg: "#eb172b", fg: "#ffffff" },
  "Swansea City": { code: "SWA", bg: "#ffffff", fg: "#111111" },
  "Swindon Town": { code: "SWI", bg: "#da1f26", fg: "#ffffff" },
  "Tottenham Hotspur": { code: "TOT", bg: "#ffffff", fg: "#132257" },
  Watford: { code: "WAT", bg: "#fbee23", fg: "#111111" },
  "West Bromwich Albion": { code: "WBA", bg: "#122f67", fg: "#ffffff" },
  "West Ham United": { code: "WHU", bg: "#7a263a", fg: "#1bb1e7" },
  "Wigan Athletic": { code: "WIG", bg: "#1d59af", fg: "#ffffff" },
  Wimbledon: { code: "WIM", bg: "#1a2c6b", fg: "#ffe200" },
  "Wolverhampton Wanderers": { code: "WOL", bg: "#fdb913", fg: "#231f20" },
  // LaLiga
  "Real Madrid": { code: "RMA", bg: "#ffffff", fg: "#1b2a6b" },
  Barcelona: { code: "BAR", bg: "#a50044", fg: "#edbb00" },
  "Atlético Madrid": { code: "ATM", bg: "#cb3524", fg: "#ffffff" },
  "Athletic Club": { code: "ATH", bg: "#ee2523", fg: "#ffffff" },
  Villarreal: { code: "VIL", bg: "#ffe667", fg: "#005187" },
  "Real Betis": { code: "BET", bg: "#00954c", fg: "#ffffff" },
  "Real Sociedad": { code: "RSO", bg: "#0067b1", fg: "#ffffff" },
  "Celta Vigo": { code: "CEL", bg: "#8ac3ee", fg: "#e5254e" },
  "Rayo Vallecano": { code: "RAY", bg: "#ffffff", fg: "#e53027" },
  Osasuna: { code: "OSA", bg: "#d91a21", fg: "#0a346f" },
  Valencia: { code: "VAL", bg: "#ffffff", fg: "#ee3524" },
  Getafe: { code: "GET", bg: "#005999", fg: "#ffffff" },
  Espanyol: { code: "ESP", bg: "#007fc8", fg: "#ffffff" },
  Sevilla: { code: "SEV", bg: "#ffffff", fg: "#d71920" },
  Levante: { code: "LEV", bg: "#004b9d", fg: "#b4053f" },
  "Alavés": { code: "ALA", bg: "#0761af", fg: "#ffffff" },
  "Deportivo La Coruña": { code: "DEP", bg: "#1b4f9c", fg: "#ffffff" },
  Elche: { code: "ELC", bg: "#ffffff", fg: "#05642c" },
  "Racing Santander": { code: "RAC", bg: "#ffffff", fg: "#00804a" },
  "Málaga": { code: "MAL", bg: "#4a90d9", fg: "#ffffff" },
  // Serie A
  Inter: { code: "INT", bg: "#0068a8", fg: "#ffffff" },
  "AC Milan": { code: "MIL", bg: "#fb090b", fg: "#000000" },
  Napoli: { code: "NAP", bg: "#12a0d7", fg: "#ffffff" },
  Juventus: { code: "JUV", bg: "#000000", fg: "#ffffff" },
  Roma: { code: "ROM", bg: "#8e1f2f", fg: "#f0bc42" },
  Atalanta: { code: "ATA", bg: "#1e71b8", fg: "#ffffff" },
  Como: { code: "COM", bg: "#003da5", fg: "#ffffff" },
  Lazio: { code: "LAZ", bg: "#87d8f7", fg: "#15366f" },
  Fiorentina: { code: "FIO", bg: "#482e92", fg: "#ffffff" },
  Bologna: { code: "BOL", bg: "#a21c26", fg: "#1a2f48" },
  Torino: { code: "TOR", bg: "#8a1e03", fg: "#ffffff" },
  Sassuolo: { code: "SAS", bg: "#00a752", fg: "#000000" },
  Genoa: { code: "GEN", bg: "#a50034", fg: "#002350" },
  Udinese: { code: "UDI", bg: "#ffffff", fg: "#000000" },
  Venezia: { code: "VEN", bg: "#000000", fg: "#f37021" },
  Cagliari: { code: "CAG", bg: "#a50032", fg: "#00285e" },
  Parma: { code: "PAR", bg: "#ffd200", fg: "#1b4094" },
  Monza: { code: "MON", bg: "#e30613", fg: "#ffffff" },
  Lecce: { code: "LEC", bg: "#ffe600", fg: "#d71920" },
  Frosinone: { code: "FRO", bg: "#ffde00", fg: "#0b3d91" },
  // Bundesliga
  "Bayern Munich": { code: "FCB", bg: "#dc052d", fg: "#ffffff" },
  "Borussia Dortmund": { code: "BVB", bg: "#fde100", fg: "#000000" },
  "Bayer Leverkusen": { code: "B04", bg: "#e32221", fg: "#000000" },
  "RB Leipzig": { code: "RBL", bg: "#ffffff", fg: "#dd0741" },
  Stuttgart: { code: "VFB", bg: "#ffffff", fg: "#e32219" },
  Hoffenheim: { code: "TSG", bg: "#1961b5", fg: "#ffffff" },
  "Eintracht Frankfurt": { code: "SGE", bg: "#000000", fg: "#e1000f" },
  Freiburg: { code: "SCF", bg: "#000000", fg: "#ffffff" },
  "Mainz 05": { code: "M05", bg: "#c3141e", fg: "#ffffff" },
  "Borussia Mönchengladbach": { code: "BMG", bg: "#ffffff", fg: "#00a650" },
  Augsburg: { code: "FCA", bg: "#ba3733", fg: "#46714d" },
  "Werder Bremen": { code: "SVW", bg: "#1d9053", fg: "#ffffff" },
  "Köln": { code: "KOE", bg: "#ffffff", fg: "#ed1c24" },
  "Union Berlin": { code: "FCU", bg: "#eb1923", fg: "#ffffff" },
  Hamburg: { code: "HSV", bg: "#ffffff", fg: "#0a3f86" },
  "Schalke 04": { code: "S04", bg: "#004d9d", fg: "#ffffff" },
  "SV Elversberg": { code: "SVE", bg: "#000000", fg: "#ffffff" },
  Paderborn: { code: "SCP", bg: "#00519e", fg: "#ffffff" },
  // Ligue 1
  "Paris Saint-Germain": { code: "PSG", bg: "#004170", fg: "#da291c" },
  Lyon: { code: "OL", bg: "#ffffff", fg: "#14387f" },
  Monaco: { code: "ASM", bg: "#e51b22", fg: "#ffffff" },
  Rennes: { code: "SRF", bg: "#e13327", fg: "#000000" },
  Lille: { code: "LIL", bg: "#e01e13", fg: "#ffffff" },
  Marseille: { code: "OM", bg: "#ffffff", fg: "#2faee0" },
  Lens: { code: "RCL", bg: "#ffd700", fg: "#e30613" },
  "Paris FC": { code: "PFC", bg: "#1a2a4a", fg: "#ffffff" },
  Strasbourg: { code: "RCS", bg: "#009fe3", fg: "#ffffff" },
  Nice: { code: "NIC", bg: "#c4102e", fg: "#000000" },
  Brest: { code: "BRS", bg: "#e30613", fg: "#ffffff" },
  Angers: { code: "SCO", bg: "#000000", fg: "#ffffff" },
  Toulouse: { code: "TFC", bg: "#5a2a82", fg: "#ffffff" },
  Lorient: { code: "FCL", bg: "#f58113", fg: "#000000" },
  Auxerre: { code: "AJA", bg: "#ffffff", fg: "#0b4ea2" },
  "Le Havre": { code: "HAC", bg: "#83c5ec", fg: "#1a2b4a" },
  Troyes: { code: "EST", bg: "#1a4b9c", fg: "#ffffff" },
  "Le Mans": { code: "LMF", bg: "#e30613", fg: "#ffd200" },
};

export function clubColours(name: string): ClubColours {
  return CLUBS[name] ?? { code: name.slice(0, 3).toUpperCase(), bg: "#3a4a40", fg: "#ffffff" };
}
